# Generated by Django 2.2 on 2019-04-04 13:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('PIP', 'Pipeline'), ('POW', 'Power line'), ('ELE', 'Electric truss')], max_length=3)),
                ('name', models.CharField(max_length=120)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('line', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'asset',
            },
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index', models.IntegerField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, dim=3, null=True, srid=4326)),
                ('line', django.contrib.gis.db.models.fields.LineStringField(blank=True, dim=3, null=True, srid=4326)),
            ],
            options={
                'db_table': 'frame',
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('line', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Asset')),
            ],
            options={
                'db_table': 'mission',
            },
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('roll', models.FloatField()),
                ('pitch', models.FloatField()),
                ('yaw', models.FloatField()),
                ('roll_speed', models.FloatField()),
                ('pitch_speed', models.FloatField()),
                ('yaw_speed', models.FloatField()),
                ('altitude', models.FloatField()),
                ('relative_altitude', models.FloatField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Mission')),
            ],
            options={
                'db_table': 'telemetry',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('INS', 'Insulator')], max_length=3)),
                ('status', models.CharField(choices=[('UNK', 'Unknown')], max_length=3)),
                ('confidence', models.IntegerField()),
                ('box', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Frame')),
            ],
            options={
                'db_table': 'object',
            },
        ),
        migrations.AddField(
            model_name='frame',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Mission'),
        ),
    ]
