# Generated by Django 2.2 on 2019-05-15 11:52

from django.db import migrations, models
import service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='file',
            field=models.FileField(default='WRONG_PATH', upload_to=service.models.upload_to),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(default=service.models.default_asset_name, max_length=120),
        ),
        migrations.AlterField(
            model_name='mission',
            name='name',
            field=models.CharField(default=service.models.default_mission_name, max_length=120),
        ),
        migrations.DeleteModel(
            name='MissionData',
        ),
    ]
