# Generated by Django 2.2 on 2019-05-15 13:05

from django.db import migrations, models
import service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20190515_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='file',
        ),
        migrations.AddField(
            model_name='mission',
            name='video_file',
            field=models.FileField(default='WRONG_PATH', upload_to=service.models.upload_to),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='VideoData',
        ),
    ]
