# Generated by Django 2.2 on 2019-05-16 11:29

from django.db import migrations, models
import django.db.models.deletion
import service.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20190515_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('roll', models.FloatField(blank=True, null=True)),
                ('pitch', models.FloatField(blank=True, null=True)),
                ('yaw', models.FloatField(blank=True, null=True)),
                ('roll_speed', models.FloatField(blank=True, null=True)),
                ('pitch_speed', models.FloatField(blank=True, null=True)),
                ('yaw_speed', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'telemetry_attribute',
            },
        ),
        migrations.CreateModel(
            name='TelemetryPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('relative_altitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'telemetry_position',
            },
        ),
        migrations.AlterField(
            model_name='mission',
            name='video_file',
            field=models.FileField(upload_to=service.models.upload_to),
        ),
        migrations.DeleteModel(
            name='Telemetry',
        ),
        migrations.AddField(
            model_name='telemetryposition',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetries_pos', to='service.Mission'),
        ),
        migrations.AddField(
            model_name='telemetryattribute',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetries_att', to='service.Mission'),
        ),
    ]
