# Generated by Django 2.2 on 2019-05-16 12:05

from django.db import migrations, models
import service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20190516_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame',
            name='location',
        ),
        migrations.AddField(
            model_name='frame',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='frame',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mission',
            name='video_file',
            field=models.FileField(upload_to=service.models.upload_to),
        ),
    ]
