# Generated by Django 2.2 on 2019-05-16 12:05

from django.db import migrations, models
import service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20190516_1205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Object',
            new_name='Anomaly',
        ),
        migrations.AlterField(
            model_name='mission',
            name='video_file',
            field=models.FileField(upload_to=service.models.upload_to),
        ),
    ]
