# Generated by Django 2.2 on 2019-05-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20190516_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='depth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='frame',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='frame',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
