# Generated by Django 2.2 on 2019-05-17 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20190516_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomaly',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_anomalies', to='service.Frame'),
        ),
    ]
