# Generated by Django 2.2 on 2019-05-22 14:11

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_auto_20190517_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='geometry',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
    ]
