# Generated by Django 2.2 on 2019-05-24 07:37

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_auto_20190522_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='geometry',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
    ]
