# Generated by Django 2.2 on 2019-05-24 10:24

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_auto_20190524_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
    ]
