# Generated by Django 2.2 on 2019-05-27 07:19b2852a5c94b6

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_auto_20190524_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missionvideo',
            name='mission',
        ),
        migrations.AddField(
            model_name='mission',
            name='mission_video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vid_missions', to='service.MissionVideo'),
        ),
    ]
