# Generated by Django 2.2 on 2019-05-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_remove_missionvideo_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
