# Generated by Django 2.2 on 2019-05-30 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_mission_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missionvideo',
            old_name='video_file',
            new_name='mission_file',
        ),
    ]
