# Generated by Django 2.2 on 2019-05-30 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_auto_20190530_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='mission_video',
            new_name='mission_file',
        ),
    ]
